/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Soal1.ManajamenDataKaryawan;


import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Desi
 */
public class MainUIKaryawan extends javax.swing.JFrame {
    private final DefaultTableModel tableModel;
    private final Perusahaan Perusahaan = new Perusahaan();

    /**
     * Creates new form MainKaryawan
     */
    public MainUIKaryawan() {
        initComponents();    
        String[] columnNames = {"ID", "Nama", "Posisi", "Gaji"};
        tableModel = new DefaultTableModel(columnNames, 0);
        tableKaryawan.setModel(tableModel);
        loadKaryawan();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NamaKaryawanField = new javax.swing.JTextField();
        IdKaryawanField = new javax.swing.JTextField();
        GajiKaryawanField = new javax.swing.JTextField();
        PosisiKaryawanField = new javax.swing.JTextField();
        AddKaryawanBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKaryawan = new javax.swing.JTable();
        UpdateKaryawanBtn = new javax.swing.JButton();
        DeleteKaryawanBtn = new javax.swing.JButton();
        CariPosisiField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CariIdField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 10, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manajemen Data Karyawan");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Posisi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Gaji");

        NamaKaryawanField.setBackground(new java.awt.Color(255, 255, 255));
        NamaKaryawanField.setForeground(new java.awt.Color(0, 0, 0));
        NamaKaryawanField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        IdKaryawanField.setBackground(new java.awt.Color(255, 255, 255));
        IdKaryawanField.setForeground(new java.awt.Color(0, 0, 0));
        IdKaryawanField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        GajiKaryawanField.setBackground(new java.awt.Color(255, 255, 255));
        GajiKaryawanField.setForeground(new java.awt.Color(0, 0, 0));
        GajiKaryawanField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        PosisiKaryawanField.setBackground(new java.awt.Color(255, 255, 255));
        PosisiKaryawanField.setForeground(new java.awt.Color(0, 0, 0));
        PosisiKaryawanField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddKaryawanBtn.setText("Tambah");
        AddKaryawanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddKaryawanBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(IdKaryawanField))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(GajiKaryawanField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addGap(4, 4, 4))
                            .addComponent(NamaKaryawanField)
                            .addComponent(PosisiKaryawanField))))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddKaryawanBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(IdKaryawanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NamaKaryawanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PosisiKaryawanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(GajiKaryawanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddKaryawanBtn)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tableKaryawan.setBackground(new java.awt.Color(204, 204, 204));
        tableKaryawan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 3, 29), 1, true));
        tableKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Posisi", "Gaji"
            }
        ));
        jScrollPane1.setViewportView(tableKaryawan);

        UpdateKaryawanBtn.setText("Update");
        UpdateKaryawanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateKaryawanBtnActionPerformed(evt);
            }
        });

        DeleteKaryawanBtn.setText("Delete");
        DeleteKaryawanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteKaryawanBtnActionPerformed(evt);
            }
        });

        CariPosisiField.setForeground(new java.awt.Color(0, 0, 0));
        CariPosisiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariPosisiFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Cari Posisi");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Cari ID");

        CariIdField.setForeground(new java.awt.Color(0, 0, 0));
        CariIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariIdFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(UpdateKaryawanBtn)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteKaryawanBtn))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CariIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CariPosisiField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CariPosisiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(CariIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateKaryawanBtn)
                    .addComponent(DeleteKaryawanBtn))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(175, 175, 175))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddKaryawanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddKaryawanBtnActionPerformed
        // TODO add your handling code here:
        //ambil input dari field
        String id   =  IdKaryawanField.getText().trim();
        String nama =  NamaKaryawanField.getText().trim();
        String posisi = PosisiKaryawanField.getText().trim();
        String gajiStr = GajiKaryawanField.getText().trim().replace(",", ".");
        //Jika ada kolom tidak diisi
        if (id.isEmpty() || nama.isEmpty() || posisi.isEmpty() || gajiStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Id, nama, posisi, gaji harus diisi.");
            return;
        }
        //Validasi Gaji
        double gaji;
        try {
            gaji = Double.parseDouble(gajiStr);
            if (gaji < 0) {
                JOptionPane.showMessageDialog(this, "Gaji tidak boleh negatif");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format gaji tidak valid");
            return;
        }
        //Buat objek karyawan baru dan tambahkan ke data perusahaan
        Karyawan newKaryawan = null;
        try {
            newKaryawan = new Karyawan(id, nama, posisi, gaji);
        }  catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
            return;
        }
        boolean success = Perusahaan.tambahKaryawan(newKaryawan);
        JOptionPane.showMessageDialog(this, "Karyawan berhasil ditambahkan!");
        loadKaryawan(); 
        IdKaryawanField.setText("");
        NamaKaryawanField.setText("");
        PosisiKaryawanField.setText(""); 
        GajiKaryawanField.setText("");
    }//GEN-LAST:event_AddKaryawanBtnActionPerformed

    // Fungsi bantu untuk mengambil nilai dari tabel dengan validasi null
    private String safeValueAt(int row, int col, String fieldName) {
    Object val = tableKaryawan.getValueAt(row, col);
    if (val == null) {
        JOptionPane.showMessageDialog(this, "Column " + fieldName + " is invalid");
        throw new NullPointerException("Invalid value in " + fieldName);
    }
    return val.toString();
}
    private void UpdateKaryawanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateKaryawanBtnActionPerformed
    //baris kolom dalam tabel dipilih terlebih dahulu
    int selectedRow = tableKaryawan.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih Karyawan untuk di-update");
        return;
    }
  
    try {
        //ambil data dari tabel
        String id = safeValueAt(selectedRow, 0, "ID");
        String oldName = safeValueAt(selectedRow, 1, "Nama");
        String oldPosisi = safeValueAt(selectedRow, 2, "Posisi");
        double oldGaji = Double.parseDouble(safeValueAt(selectedRow, 3, "Gaji"));
         // Ambil input baru
        String namaInput = NamaKaryawanField.getText().trim();
        String posisiInput = PosisiKaryawanField.getText().trim();
        String gajiInput = GajiKaryawanField.getText().trim();
        // Gunakan input baru jika ada, atau pertahankan data lama
        String Nama = namaInput.isEmpty() ? oldName : namaInput;
        String Posisi = posisiInput.isEmpty() ? oldPosisi : posisiInput;
        double Gaji = gajiInput.isEmpty() ? oldGaji : Double.parseDouble(gajiInput);
        // Validasi gaji tidak negatif
        if (Gaji < 0) {
            JOptionPane.showMessageDialog(this, "Gaji tidak boleh negatif");
            return;
        }
        // Buat objek karyawan baru untuk update
        Karyawan updateKaryawan = new Karyawan(id, Nama, Posisi, Gaji); // Pastikan konstruktor mendukung ID
        boolean success = Perusahaan.updateKaryawan(updateKaryawan);

        if (success) {
            JOptionPane.showMessageDialog(this, "Data berhasil diubah");
            clearMainUIKaryawan();
            loadKaryawan();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal diubah");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error saat update: " + e.getMessage());
        e.printStackTrace();
    }
    }
        private void clearMainUIKaryawan() {
        NamaKaryawanField.setText("");
        PosisiKaryawanField.setText("");
        GajiKaryawanField.setText("");
        }   
        /*                                  
    }//GEN-LAST:event_UpdateKaryawanBtnActionPerformed
*/
    private void DeleteKaryawanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteKaryawanBtnActionPerformed
        // TODO add your handling code here:
        //Baris dipilih dari tabel
        int selectedRow = tableKaryawan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih karyawan");
            return;
        }
        //Ambil ID dari tabel
        String KaryawanId = (String) tableKaryawan.getValueAt(selectedRow, 0);
        // Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin menghapus data ini",
            "", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                boolean deleted = Perusahaan.hapusKaryawan(KaryawanId);
            if (deleted) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                loadKaryawan(); 
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error" + ex.getMessage());
        }
    }       
    }//GEN-LAST:event_DeleteKaryawanBtnActionPerformed

    private void CariPosisiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariPosisiFieldActionPerformed
     // TODO add your handling code here:
    String keyword = CariPosisiField.getText().trim().toLowerCase();
    // Tampilkan semua jika kosong
    if (keyword.isEmpty()) {
        loadKaryawan(); 
        return;
    }
    // Kosongkan tabel
    tableModel.setRowCount(0); 
    for (Karyawan k : Perusahaan.SemuaKaryawan()) {
        if (k.getPosisi().toLowerCase().contains(keyword)) {
            tableModel.addRow(new Object[]{
                k.getId(), k.getNama(), k.getPosisi(), k.getGaji()
            });
        }
    }
    }//GEN-LAST:event_CariPosisiFieldActionPerformed

    private void CariIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariIdFieldActionPerformed
        // TODO add your handling code here:
        String keyword = CariIdField.getText().trim().toLowerCase();
        // Jika kosong, tampilkan semua data
        if (keyword.isEmpty()) {
            loadKaryawan(); 
            return;
        }
        // Kosongkan tabel
        tableModel.setRowCount(0); 
        for (Karyawan k : Perusahaan.SemuaKaryawan()) {
            if (k.getId().toLowerCase().contains(keyword)) {
                tableModel.addRow(new Object[]{
                    k.getId(), k.getNama(), k.getPosisi(), k.getGaji()
                });
            }
        }

    }//GEN-LAST:event_CariIdFieldActionPerformed
/*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUIKaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddKaryawanBtn;
    private javax.swing.JTextField CariIdField;
    private javax.swing.JTextField CariPosisiField;
    private javax.swing.JButton DeleteKaryawanBtn;
    private javax.swing.JTextField GajiKaryawanField;
    private javax.swing.JTextField IdKaryawanField;
    private javax.swing.JTextField NamaKaryawanField;
    private javax.swing.JTextField PosisiKaryawanField;
    private javax.swing.JButton UpdateKaryawanBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKaryawan;
    // End of variables declaration//GEN-END:variables

    // Menampilkan seluruh data karyawan ke dalam tabel
    private void loadKaryawan() {
    tableModel.setRowCount(0); 
    List<Karyawan> karyawan = Perusahaan.SemuaKaryawan();
    for (Karyawan karyawans : karyawan) {
        tableModel.addRow(new Object[]{
            karyawans.getId(), 
            karyawans.getNama(), 
            karyawans.getPosisi(), 
            karyawans.getGaji(), 
        });
    }
}
    }

