/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Soal3.LotreGosok;
import Soal3.LotreGosok.LotreBoard;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author Desi
 */
public class MainUILotre extends javax.swing.JFrame {
    private LotreBoard board;
    private JButton[][] buttons;

    /**
     * Creates new form MainUILotre
     */
    public MainUILotre() {
        initComponents();
        board = new LotreBoard();
        setupButtons();
    }

        private void setupButtons() {
            buttons = new JButton[][] {
                { button00, button01, button02, button03, button04 },
                { button10, button11, button12, button13, button14 },
                { button20, button21, button22, button23, button24 },
                { button30, button31, button32, button33, button34 }
            };
            
            for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[0].length; j++) {
            final int row = i;
            final int col = j;

            buttons[i][j].addActionListener(e -> handleClick(row, col));
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button10 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        button30 = new javax.swing.JButton();
        button00 = new javax.swing.JButton();
        button31 = new javax.swing.JButton();
        button01 = new javax.swing.JButton();
        button21 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button32 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button02 = new javax.swing.JButton();
        button03 = new javax.swing.JButton();
        button13 = new javax.swing.JButton();
        button04 = new javax.swing.JButton();
        button14 = new javax.swing.JButton();
        button33 = new javax.swing.JButton();
        button34 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();
        button23 = new javax.swing.JButton();
        button24 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(8, 33, 45));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lottery Gosok");

        button10.setBackground(new java.awt.Color(255, 255, 255));
        button10.setForeground(new java.awt.Color(0, 0, 0));
        button10.setText("*");

        button20.setBackground(new java.awt.Color(255, 255, 255));
        button20.setForeground(new java.awt.Color(0, 0, 0));
        button20.setText("*");

        button30.setBackground(new java.awt.Color(255, 255, 255));
        button30.setForeground(new java.awt.Color(0, 0, 0));
        button30.setText("*");

        button00.setBackground(new java.awt.Color(255, 255, 255));
        button00.setForeground(new java.awt.Color(0, 0, 0));
        button00.setText("*");

        button31.setBackground(new java.awt.Color(255, 255, 255));
        button31.setForeground(new java.awt.Color(0, 0, 0));
        button31.setText("*");

        button01.setBackground(new java.awt.Color(255, 255, 255));
        button01.setForeground(new java.awt.Color(0, 0, 0));
        button01.setText("*");

        button21.setBackground(new java.awt.Color(255, 255, 255));
        button21.setForeground(new java.awt.Color(0, 0, 0));
        button21.setText("*");

        button11.setBackground(new java.awt.Color(255, 255, 255));
        button11.setForeground(new java.awt.Color(0, 0, 0));
        button11.setText("*");

        button32.setBackground(new java.awt.Color(255, 255, 255));
        button32.setForeground(new java.awt.Color(0, 0, 0));
        button32.setText("*");

        button12.setBackground(new java.awt.Color(255, 255, 255));
        button12.setForeground(new java.awt.Color(0, 0, 0));
        button12.setText("*");

        button02.setBackground(new java.awt.Color(255, 255, 255));
        button02.setForeground(new java.awt.Color(0, 0, 0));
        button02.setText("*");

        button03.setBackground(new java.awt.Color(255, 255, 255));
        button03.setForeground(new java.awt.Color(0, 0, 0));
        button03.setText("*");

        button13.setBackground(new java.awt.Color(255, 255, 255));
        button13.setForeground(new java.awt.Color(0, 0, 0));
        button13.setText("*");

        button04.setBackground(new java.awt.Color(255, 255, 255));
        button04.setForeground(new java.awt.Color(0, 0, 0));
        button04.setText("*");

        button14.setBackground(new java.awt.Color(255, 255, 255));
        button14.setForeground(new java.awt.Color(0, 0, 0));
        button14.setText("*");

        button33.setBackground(new java.awt.Color(255, 255, 255));
        button33.setForeground(new java.awt.Color(0, 0, 0));
        button33.setText("*");

        button34.setBackground(new java.awt.Color(255, 255, 255));
        button34.setForeground(new java.awt.Color(0, 0, 0));
        button34.setText("*");

        button22.setBackground(new java.awt.Color(255, 255, 255));
        button22.setForeground(new java.awt.Color(0, 0, 0));
        button22.setText("*");

        button23.setBackground(new java.awt.Color(255, 255, 255));
        button23.setForeground(new java.awt.Color(0, 0, 0));
        button23.setText("*");

        button24.setBackground(new java.awt.Color(255, 255, 255));
        button24.setForeground(new java.awt.Color(0, 0, 0));
        button24.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button24, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button32, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button33, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button00, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button01, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button02, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button03, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button04, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(69, 69, 69))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button00)
                    .addComponent(button01)
                    .addComponent(button02)
                    .addComponent(button03)
                    .addComponent(button04))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button10)
                    .addComponent(button11)
                    .addComponent(button12)
                    .addComponent(button13)
                    .addComponent(button14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button20)
                    .addComponent(button21)
                    .addComponent(button22)
                    .addComponent(button23)
                    .addComponent(button24))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button30)
                    .addComponent(button31)
                    .addComponent(button32)
                    .addComponent(button33)
                    .addComponent(button34))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUILotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUILotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUILotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUILotre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUILotre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button00;
    private javax.swing.JButton button01;
    private javax.swing.JButton button02;
    private javax.swing.JButton button03;
    private javax.swing.JButton button04;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button13;
    private javax.swing.JButton button14;
    private javax.swing.JButton button20;
    private javax.swing.JButton button21;
    private javax.swing.JButton button22;
    private javax.swing.JButton button23;
    private javax.swing.JButton button24;
    private javax.swing.JButton button30;
    private javax.swing.JButton button31;
    private javax.swing.JButton button32;
    private javax.swing.JButton button33;
    private javax.swing.JButton button34;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void handleClick(int row, int col) {
        if (board.isRevealed(row, col)) {
            JOptionPane.showMessageDialog(this, "Kotak sudah dibuka!");
            return;
        }

        board.reveal(row, col);

        if (board.isBomb(row, col)) {
            buttons[row][col].setText("X");
            buttons[row][col].setEnabled(false);
            revealAll();
            JOptionPane.showMessageDialog(this, "BOOM! Anda menemukan bom! Permainan Berakhir.");
            disableAll();
        } else {
            buttons[row][col].setText("O");
            buttons[row][col].setEnabled(false);

            if (board.isWin()) {
                revealAll();
                JOptionPane.showMessageDialog(this, "Selamat anda menang!");
                disableAll();
            }
        }
    }

    private void revealAll() {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[0].length; j++) {
                if (!board.isRevealed(i, j)) {
                    if (board.isBomb(i, j)) {
                        buttons[i][j].setText("X");
                    } else {
                        buttons[i][j].setText("O");
                    }
                }
                buttons[i][j].setEnabled(false);
            }
        }
    }


private void disableAll() {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[0].length; j++) {
                buttons[i][j].setEnabled(false);
            }
        }
    }
}
